services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: career-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      # Prevents local python virtual environments from conflicting inside the container
      - /app/venv
      - /app/.venv
    env_file:
      - ./backend/.env.local
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000/api
        - NEXT_PUBLIC_GOOGLE_CLIENT_ID=448585824184-hnjidk5u6aa0jo4mji9shcirhaii5daf.apps.googleusercontent.com
    container_name: career-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
