# Generated by Django 6.0.6 on 2026-06-09 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_job_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('portfolio', models.URLField(blank=True, max_length=500, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('degree_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_company', models.CharField(blank=True, max_length=255, null=True)),
                ('total_experience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_ctc', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_ctc', models.CharField(blank=True, max_length=100, null=True)),
                ('notice_period', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
        ),
    ]
