export const departmentConfig = {
  "Engineering & Development": {
    roles: ["Frontend Developer", "Backend Developer", "Fullstack Developer"],
    requiredSkills: ["React", "Next.js", "Node.js", "MongoDB", "PostgreSQL"],
    goodToHaveSkills: ["Docker", "AWS", "TypeScript", "Redis"],
    portfolioLabel: "GitHub profile required?",
    assignmentLabel: "Coding test round?",
  },
  "Design": {
    roles: ["UI/UX Designer", "Graphic Designer", "Motion Designer", "Video Editor"],
    requiredSkills: ["Figma", "Photoshop", "Illustrator"],
    goodToHaveSkills: ["After Effects", "Premiere Pro", "Canva"],
    portfolioLabel: "Behance / Dribbble required?",
    assignmentLabel: "Design assignment round?",
  },
  "Product": {
    roles: ["Product Manager", "QA Engineer", "Testing Engineer"],
    requiredSkills: ["Jira", "Notion", "Figma basics", "Excel"],
    goodToHaveSkills: ["Agile", "Scrum", "Postman", "Selenium"],
    portfolioLabel: "Portfolio required?",
    assignmentLabel: "Case study round?",
  },
  "Hardware & Tech": {
    roles: ["PC Build Technician", "Hardware Consultant", "Component Sourcing Specialist"],
    requiredSkills: ["PC Assembly", "Component Knowledge", "Troubleshooting"],
    goodToHaveSkills: ["Overclocking", "Watercooling", "Inventory Management"],
    portfolioLabel: "Work sample required?",
    assignmentLabel: "Practical test round?",
  },
  "Marketing & Content": {
    roles: ["Social Media Manager", "Content Creator", "SEO Specialist", "Video Editor"],
    requiredSkills: ["Instagram", "YouTube", "Canva", "Copywriting"],
    goodToHaveSkills: ["SEO", "Google Analytics", "Premiere Pro", "Meta Ads"],
    portfolioLabel: "Portfolio / social page required?",
    assignmentLabel: "Content assignment round?",
  },
  "Sales & Business Development": {
    roles: ["Sales Executive", "B2B Partnership Manager", "Business Development Executive"],
    requiredSkills: ["Lead Generation", "Cold Calling", "CRM basics", "Email Outreach"],
    goodToHaveSkills: ["HubSpot", "Zoho CRM", "Negotiation", "Market Research"],
    portfolioLabel: "Work sample required?",
    assignmentLabel: "Assignment round?",
  },
  "Operations & Logistics": {
    roles: ["Logistics Coordinator", "Inventory Manager", "Warehouse Executive", "Operations Executive"],
    requiredSkills: ["Excel", "Inventory Management", "Dispatch Coordination"],
    goodToHaveSkills: ["Tally", "ERP systems", "Supply Chain basics"],
    portfolioLabel: "Work sample required?",
    assignmentLabel: "Assignment round?",
  },
  "Customer Support": {
    roles: ["Customer Support Executive", "Technical Support Executive", "Customer Success Executive"],
    requiredSkills: ["Email Support", "Chat Support", "Ticket Handling", "CRM basics"],
    goodToHaveSkills: ["Freshdesk", "Zendesk", "PC Knowledge", "Regional Language"],
    portfolioLabel: "Work sample required?",
    assignmentLabel: "Assignment round?",
  },
  "Finance & Accounts": {
    roles: ["Accountant", "Finance Executive", "Finance Analyst", "Accounts Executive"],
    requiredSkills: ["Tally ERP", "Excel", "GST", "TDS"],
    goodToHaveSkills: ["SAP", "Zoho Books", "MIS Reporting", "Audit"],
    portfolioLabel: "Work sample required?",
    assignmentLabel: "Assignment round?",
  },
  "HR": {
    roles: ["HR Executive", "Talent Acquisition Executive", "HR Operations Executive"],
    requiredSkills: ["Resume Screening", "Job Posting", "Interview Scheduling", "Excel"],
    goodToHaveSkills: ["LinkedIn Recruiter", "ATS tools", "Onboarding", "Labor Law basics"],
    portfolioLabel: "Work sample required?",
    assignmentLabel: "Assignment round?",
  },
  "Custom": {
    roles: [],
    requiredSkills: [],
    goodToHaveSkills: [],
    portfolioLabel: "Portfolio / Work sample required?",
    assignmentLabel: "Assignment round?",
  }
};
