from rest_framework import serializers
from .models import Job

class JobSerializer(serializers.ModelSerializer):
    created_by_email = serializers.EmailField(source='created_by.email', read_only=True)

    class Meta:
        model = Job
        fields = [
            'id',
            'job_title',
            'role',
            'department',
            'employment_type',
            'candidate_level',
            'number_of_openings',
            'internship_duration',
            'work_mode',
            'office_location',
            'shift_timing',
            'application_deadline',
            'expected_joining_date',
            'stipend_amount',
            'stipend_visible',
            'ctc_min',
            'ctc_max',
            'salary_visible',
            'probation_period',
            'probation_stipend',
            'notice_period',
            'performance_bonus',
            'performance_bonus_description',
            'other_compensation',
            'min_education',
            'preferred_branch',
            'min_cgpa',
            'year_of_study',
            'graduation_year',
            'min_experience',
            'max_experience',
            'required_skills',
            'good_to_have_skills',
            'portfolio_required',
            'assignment_round',
            'assignment_description',
            'certifications',
            'previous_industry_experience',
            'led_team',
            'roles_responsibilities',
            'what_intern_learns',
            'what_we_offer',
            'growth_path',
            'team_structure',
            'perks_benefits',
            'additional_info',
            'screening_question_1',
            'screening_question_2',
            'screening_question_3',
            'status',
            'scheduled_date',
            'notify_team',
            'created_by',
            'created_by_email',
            'created_at',
            'updated_at',
        ]
        read_only_fields = ['id', 'created_by', 'created_at', 'updated_at']
