# Generated by Django 6.0.6 on 2026-06-09 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('employment_type', models.CharField(blank=True, choices=[('internship', 'Internship'), ('fulltime', 'Full-time')], max_length=50, null=True)),
                ('description', models.TextField()),
                ('skills', models.JSONField(blank=True, default=list)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_frequency', models.CharField(default='annual', max_length=20)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('application_template', models.CharField(default='fulltime', max_length=50)),
                ('customize_resume', models.BooleanField(default=True)),
                ('customize_cover_letter', models.BooleanField(default=True)),
                ('customize_portfolio', models.BooleanField(default=False)),
                ('customize_phone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
